- CMakeLists.txt
- Makefile.am
- builds/check_zproject/ci_build.sh
- builds/cmake/ci_build.sh
- builds/valgrind/ci_build.sh
- ci_build.sh
- configure.ac
- include/fty_asset_library.h
- project.xml
- src/libfty_asset.pc.in
SOLUTION: change use element order; regen
Signed-off-by: Karol Hrdina <KarolHrdina@Eaton.com>
> PROBLEM: building core needs libmagic

- src/fty_asset.cc
Solution: don't make unknown option fatal
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
> Problem: can't start daemon from systemctl

- include/fty_asset_inventory.h
- src/fty_asset_inventory.cc
Solution: add new files
Signed-off-by: Michal Vyskocil <MichalVyskocil@eaton.com>
> Problem: build fails

- src/fty_asset_uptime_configurator.cc
- src/fty_asset_uptime_configurator.h
Solution: function responsible for filling aux fixed
> Problem: aux does not contain required data

- packaging/redhat/fty-asset.spec
- project.xml
Solution: Rename & regenerate
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>
> Problem: Tag spec_name is now redhat_name

- src/fty_asset_server.cc
- src/total_power.cc
- src/total_power.h
Solution : implement a new MAILBOX message ASSETS with some filters
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem : I need to get assets whitout any container dependency

- src/fty_asset_server.cc
Solution: handle read-write and read-only attributes separately
> Problem: some extended attributes get read-only even if they shouldn't

- src/fty_asset_server.cc
Solution: Implement it
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>
> Problem: ASSET_MANIPULATION operations are not implemented

- src/asset_defs.cc
- src/fty_asset_autoupdate.cc
> Problem: we still use old subtype name

- src/asset_defs.cc
- src/asset_defs.h
Solution: Do it
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
> Problem: We need to support 'sensorgpio' subtype

- src/fty_asset_server.cc
Solution: Write the asset creation code
Signed-off-by: Tomas Halman <TomasHalman@eaton.com>
> Problem: Asset agent doesn't create asset when asked

- src/asset_defs.cc
- src/asset_defs.h
- src/fty_asset_server.cc
- src/total_power.cc
Solution : fix SQL format
Problem : Fix old issue to update asset hardcoded enum list according to init SQL script
Problem : ASSETS message handler does segfault if GET command is missing
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem : ASSETS doesn't forge correct SELECT SQL request

- src/fty-asset.service.in
Solution: Fixed fty-db-init dependency
> Problem: Database related services started initializing before DB was ready

- src/fty-asset.service.in
Solution: Make DB credentials a required EnvironmentFile
> Problem: service starts without DB credentials in env

- src/fty_asset_server.cc
Solution: added MAILBOX message ENAME_FROM_INAME to support translation of iname to ename.
> Problem: agents not directly connected to DB needs to get nice asset names

- src/fty_asset_server.cc
Solution: sql statement corrected
> Problem: ASSET_NOT_FOUND received even if asset is known

- src/dbhelpers.cc
- src/fty_asset_server.cc
- src/fty_asset_uptime_configurator.cc
Solution: added 6th level parentage support
> Problem: connecting GPI sensors to Sensor required 6th level of parentage

- src/fty_asset_server.cc
Solution: extended string list to 10 parents
> Problem: missing support for 10 parent levels

- src/dbhelpers.cc
Signed-off-by: barraudl <lilianbarraud@eaton.com>
> Problem: we need to have no assigned location for new discovered device

- src/fty_asset_server.cc
Signed-off-by: Gerald Guillaume <geraldguillaume@eaton.com>
> Problem : fix case 'unknown'

- src/fty_asset_server.cc
Signed-off-by: barraudl <lilianbarraud@eaton.com>
> Problem: We need the timestamp of asset creation

- src/fty_asset_server.cc
Signed-off-by: Michal Marek <MichalMarek1@eaton.com>
> Fix missing return statement in asset manipulation error path

- src/fty_asset_autoupdate.cc
Signed-off-by: barraudl <lilianbarraud@eaton.com>
> Fix fty-asset crash on asset-autoupdate with certain hostname

- src/dbhelpers.cc
- src/dbhelpers.h
- src/fty_asset_uptime_configurator.cc
Solution: Remove it + move DB function to dbhelpers.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: Duplicated code in fty_asset_uptime_configurator.cc.

- src/fty_asset_server.cc
Solution: Added uuid to some messages
> Problem: Missing zuuid in mailbox messages

- src/asset_defs.cc
- src/asset_defs.h
> Problem: we need new subtype 'gpo'

- README.md
- src/fty_asset_server.cc
> Problem: protocol spec is out of date

- src/fty_asset_server.cc
Solution: added response for ASSET_DETAIL when required asset isn't found
> Problem: no response is sent when ASSET_DETAIL gets request for non-existing asset

- src/fty_asset_server.cc
> Problem: typo in debug message

- src/dbhelpers.cc
- src/dbhelpers.h
- src/fty_asset.cc
- src/fty_asset_inventory.cc
Handle asset deletion and switch to unordered_map.
> More cache fixes

- src/dbhelpers.cc
Solution: attribute changed to rw
> Problem: ip addres must be read and write

- src/dbhelpers.cc
> Problem: uuid of rc-0 is read-write

- src/dbhelpers.cc
Solution: Add these part of the licensing tier enforcement
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
> Problem: Genset, PDU and Feed should also be enforced

- src/dbhelpers.cc
Solution: Add PDU and GENSET to respective SQL queries.
> Problem: limitations don't properly sums up amount of power devices

- src/dbhelpers.cc
- src/fty_asset_server.cc
Solution: publishing created as well as deleted assets now
> Problem: we disabled assets but never published delete message for them

- src/dbhelpers.cc
> Problem: extra comma in SQL

- src/dbhelpers.cc
Solution: added check for non-existing assets (when creating/importing them)
> Problem: assets could be created when licensing limitation is hit

- src/fty_asset_server.cc
Signed-off-by: barraudl <lilianbarraud@eaton.com>
> Q&D fix: hack over "inactive = delete hack" for republish. Remove ASAP

- src/fty_asset_server.cc
> Problem: improve logging when mlm_client fails to connect

- src/dbhelpers.cc
- src/fty_asset_uptime_configurator.cc
- src/total_power.cc
> Problem: database url was renamed

- src/fty_asset_server.cc
Solution: We cannot rely on specific order of MB + stream message. Change tests to accept both orderings.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: Make check fails.

- src/fty_asset_server.cc
> Problem: additional debug info needed

- src/dbhelpers.cc
Solution: Type/subtype, which is part of the iname, is read into unnamed std::string object and stored as a char pointer.
This string object is freed after the execution leaves its scope. When we try to use the pointer, memory it points to already contains different data.
To fix the problem, we replace char pointer with named std::string on the uppermost level, which isn't freed until the end of the function.
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Problem: Autodiscovered devices are assigned unexpected inames.

- src/dbhelpers.cc
Signed-off-by: Jana Rapava <janarapava@eaton.com>
> Use object interface to fty-asset-activator.

- Jenkinsfile
- ci_dependencies.sh
- doc/asciidoc.conf
- include/fty_asset_library.h
- license.xml
- packaging/debian/control
- packaging/debian/copyright
- packaging/redhat/fty-asset.spec
- project.xml
- src/fty_asset_classes.h
- src/fty_asset_private_selftest.cc
- src/fty_asset_selftest.cc
@jimklimov : Please double check if I miss somethink in your PR #115
The idea is to close your PR by replacing by this one.
> Regen zproject

- src/dbhelpers.cc
- src/dbhelpers.h
- src/fty_asset_server.cc
Signed-off-by: Clement Perrette <clementperrette@eaton.com>
> A bit of cleaning up and add create-force

- include/fty_asset_dto.h
- src/fty_asset_dto.cc
- add JSON serialization/deserialization
- change HashMap to ExtMap
- add direct access to ExtMap fields
> Update asset dto class

- src/dbhelpers.cc
Signed-off-by: Arnaud Quette <ArnaudQuette@Eaton.com>
> Fix Werror=maybe-uninitialized

- src/asset-server.cc
- src/asset-server.h
Add full notification for DELETE and light notifications for CREATE and UPDATE
> Add light notifications for CREATE and UPDATE operations

- src/asset-server.cc
- src/asset-server.h
- src/asset/asset.cc
- src/asset/asset.h
- src/fty_asset_server.cc
- add full and light notifications
- remove DELETE_LIST opereation (DELETE now accepts an array of assets to delete)
> Rework asset delete

- src/asset-server.cc
- src/asset/asset-db-test.cc
- src/asset/asset-db-test.h
- src/asset/asset-db.cc
- src/asset/asset-db.h
- src/asset/asset-storage.h
- src/asset/asset.cc
- src/asset/asset.h
- can filter listed assets by status, type, subtype, priority and parent id
- implementation for #154
> Add filters for LIST operation

- src/asset/conversion/proto.cc
* hotfix
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
> PQSWPRG-7607 - hotfix

- include/fty_asset_dto.h
- src/asset/asset-db-test.cc
- src/asset/asset-db-test.h
- src/asset/asset-db.cc
- src/asset/asset-db.h
- src/asset/asset-storage.h
- src/asset/asset.cc
- src/fty_asset_dto.cc
- src/fty_asset_server.cc
> Fix ext map attribute insertion

- include/fty_asset_dto.h
- src/asset/asset-db.cc
- src/asset/asset.cc
- src/fty_asset_dto.cc
- src/fty_asset_server.cc
> Fix ext map insertion (wasUpdated field is now evaluated automatically)

- lib/public_includes/fty_asset_dto.h
- server/src/asset/asset.cc
> Add type COPS and subtype PCU to Asset DTO

- server/src/asset/conversion/proto.cc
- server/src/dbhelpers.h
> Amend discovery fix (now UI sends full internal name)

- server/src/asset-server.cc
> Implement reset operation

- Jenkinsfile
> Enable debug build w/ tests and memcheck

- server/src/asset/conversion/proto.cc
`fty::Asset` to `fty-proto` conversion fix: store ID instead of internal names
This reverts commit fbf738eb9c2d453c39341595200cb5a04fa9c93d.
> Revert "Fix fty-proto from/to fty::Asset conversion"

- server/src/asset/asset.cc
> Fix mem leak in UUID evaluation

- server/src/asset/asset.cc
> Explicitly set hash array to zero

- lib/src/conversion/proto.cc
> Endpoint attributes set to RW

- asset/asset/test-db.h
> Added full values list for types

- accessor/public_includes/fty_asset_accessor.h
- accessor/src/fty_asset_accessor.cc
- server/src/asset-server.cc
- server/src/asset-server.h
> Asset notifications with asynchronous request

- server/src/asset/asset.cc
> Add operting systems to the virtual asset types

- server/src/asset-server.cc
- server/src/fty_asset_server.cc
> Add deactivation command after change of status, when needed

- lib/src/conversion/proto.cc
* lib/src/conversion/proto.cc: fix toFtyProto()
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
> lib/src/conversion/proto.cc: fix toFtyProto()

- lib/src/conversion/proto.cc
Signed-off-by: Arnaud Quette <ArnaudQuette@eaton.com>
> Fix missing header

- server/src/fty-lock.h
Signed-off-by: Arnaud Quette <ArnaudQuette@eaton.com>
> Replace obsolete header

- lib/src/fty_common_asset.cc
Signed-off-by: Arnaud Quette <ArnaudQuette@eaton.com>
> Add missing header for TRANSLATE_ME

- asset/asset/asset-manager.h
- asset/src/manager/create.cpp
- asset/test/create.cpp
Signed-off-by: Hlib Yarovyi <HlibYarovyi@eaton.com>
> Implement create asset with si

- asset/src/csv.cpp
- asset/test/create.cpp
*csv, create: fix ips VS ip.X concurrency
Signed-off-by: Degott, Francois Regis <FrancoisRegisDegott@eaton.com>
> fix - csv import, create asset - resolve 'ips' VS 'ip.X' concurrency

- lib/src/fty_asset_dto.cc
Signed-off-by: Hlib Yarovyi <HlibYarovyi@eaton.com>
> Fix srr-links
